### ISSUE TITLE
When using this action - Failing to download DB

### ISSUE THREAD

**Issue by aaron-pham** [Azure/container-scan#103]
Hi, I am attempting to use this github action, but it seems to be failing on  getting the trivy DB (?). I am using a self hosted runner, and tested on that machine if I am able to curl that url `curl https://api.github.com/repos/aquasecurity/trivy-db/releases`, this does return data.

I am kind of confused on the error, it's saying `401 Bad credentials []`, but I don't give this github action any credentials. Any ideas?

```
  - name: Scanning container
    uses: Azure/container-scan@v0
    with: 
      image-name: ${{github.sha}}
```

Error: FATAL	DB error: failed to download vulnerability DB: failed to download vulnerability DB: failed to list releases: GET https://api.github.com/repos/aquasecurity/trivy-db/releases: 401 Bad credentials []
Error: An error occurred while scanning the container image for vulnerabilities
