### ISSUE TITLE
Action could not find allowedlist file. 

### ISSUE THREAD

**Issue by JeffreyArt1** [Azure/container-scan#117]
I placed the `allowedlist.yaml` under the specified directory `.github/containerscan`, and also installed the [Scanitizer](https://github.com/apps/scanitizer).

Here's how my file looks like
```yaml
general:
  vulnerabilities:
    - CVE-2021-3807
  bestPracticeViolations:
    - CIS-DI-0005
```

Run output (first lines): 
```
Could not find allowedlist file.
/usr/bin/tar --version
tar (GNU tar) 1.30
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**Comment by koalaty-code** [comment]
@JeffreyArt1 I was having the same issue with GH Actions and it was because I was missing a step to checkout the repo in the `container-scan` job. I added the following and `container-scan` was able to detect the `allowedlist.yaml` file as expected:

```
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      ...
```

**Comment by JeffreyArt1** [comment]
@koalaty-code huge thanks man, its solved. Now I think that it's a bit of common sense to include the checkout step, but it'll be nice if it's specified in [this](https://github.com/Azure/container-scan#ignoring-vulnerabilities) section.

**Comment by tripflex** [comment]
Thanks was having this issue as well!

For those who may be wondering, I added this before scan, for example here's scanning redis:

```
  scan-public-images:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - uses: Azure/container-scan@v0.1
        env:
          DOCKER_CONTENT_TRUST: 1
        with:
          image-name: redis:7.0.7-alpine
          run-quality-checks: false
```
