### ISSUE TITLE
Error when trying to scan public image

### ISSUE THREAD

**Issue by fraserc182** [Azure/container-scan#120]
I am seeing the following error when trying to implement a simple scan of an image.
Snippet is:

```
Error: FATAL	scan error: unable to initialize a scanner: unable to initialize a docker scanner: 3 errors occurred:
Error: An error occurred while scanning container image: parsedmarc:latest for vulnerabilities.
```

Full logs are attached
[logs_10.zip](https://github.com/Azure/container-scan/files/7954641/logs_10.zip)

The github action looks like:

```
  docker_scan:
    runs-on: ubuntu-latest
    needs: docker_build_and_push
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Pull and scan parsedmarc
        uses: azure/container-scan@v0
        with:
          image-name: parsedmarc:latest
``` 

Any help would be appreciated!
