### ISSUE TITLE
Vulnerability Scanner not showing vulnerabilities

### ISSUE THREAD

**Issue by sjgupta19** [Azure/container-scan#143]
Hi,
We are using this in our ci workflow for looking at vulnerable packages. We have remediated all the packages and currently there is no vulnerability but it is still throwing an error  "_Vulnerabilities were detected in the container image_" and giving no information on the vulnerability. 
<img width="1014" alt="image" src="https://user-images.githubusercontent.com/105396748/175207858-bda23bf4-6ea6-4b3a-95ba-b7a66c9db976.png">

Also tried v0 and v0.1

**Comment by zifeo** [comment]
@sjgupta19 What happens if you run Trivy locally? Is the failing case a "secret" issue?

**Comment by scottwestover** [comment]
I also started running into this issue today, and I think the issue is tied to the latest version of trivy: `0.29.2`.

Here are a few screenshots of the issue that I am seeing:
<img width="853" alt="Screen Shot 2022-06-23 at 4 26 02 PM" src="https://user-images.githubusercontent.com/9931822/175394646-ef302512-069c-48ff-8280-620a586f6a0e.png">
<img width="1005" alt="Screen Shot 2022-06-23 at 4 26 15 PM" src="https://user-images.githubusercontent.com/9931822/175394648-11959c74-2a52-4730-b45d-7758a9293863.png">
<img width="497" alt="Screen Shot 2022-06-23 at 4 26 34 PM" src="https://user-images.githubusercontent.com/9931822/175394650-bf00ed9c-21a6-40c5-8783-2a669e9eb5e8.png">

When I run Trivy locally, I am seeing no vulnerabilities and no secrets, however when I run this action, I am getting the failure message.

However, if I update the action to use the previous version of trivy: `0.29.1`, the scan works and passes successfully. Example configuration:

```
      - name: Scan Docker Image
        uses: azure/container-scan@v0.1
        with:
          image-name: test_docker_for_scan
          username: USER
          password: ${{ secrets.GITHUB_TOKEN }}
          trivy-version: "0.29.1" 
  ```
