### ISSUE TITLE
Image name as environment variable is not parsed

### ISSUE THREAD

**Issue by bogdanbarna** [Azure/container-scan#46]
### Description

Hello. Really like this action as it bundles together some my favorite container CI utilities.
I've noticed an issue that does not seem documented anymore, though: it doesn't parse environment variables set in the job.

### Expected

When referencing the Docker image name stored as an environment variable (example below), the `container-scan` Action is able to parse it.
e.g.

```
      - name: Scan image
        uses: Azure/container-scan@v0
        with:
          image-name: $IMAGE_NAME:${{ github.sha }}
          severity-threshold: "CRITICAL"
          run-quality-checks: true
```

### What actually happens

When referencing the Docker image name stored as an environment variable, the `container-scan` Action is not able to parse it.
```
Scanning for vulnerabilties...
Error: An error occured while scanning the container image for vulnerabilities
```

### Example

I've created a [test repository to demonstrate this behavior](https://github.com/bogdanbarna/test-container-scan-action).

- [Running the action with image name stored as environment variable errors out with the cryptic message I've mentioned above](https://github.com/bogdanbarna/test-container-scan-action/actions/runs/282835402).
- [Running the action with image name hardcoded completes successfully](https://github.com/bogdanbarna/test-container-scan-action/runs/1194911110?check_suite_focus=true).

Thank you.
