### ISSUE TITLE
Allow to scan multiple image variants in one go

### ISSUE THREAD

**Issue by grzesuav** [Azure/container-scan#59]
I build several variants of the image (`alpine`/`distroless`), would it be possible to specify several images to scan instead of necessity to define scan job multiple times ?

**Comment by azooinmyluggage** [comment]
@ ammohant this looks like a fair ask. Will this change anything for the ASC scenario?

**Comment by ammohant** [comment]
@azooinmyluggage  - Supporting this will be a superset of current ASC requirements. Nothing changes for ASC as such

**Comment by azooinmyluggage** [comment]
@grzesuav It will take us a sprint or two to prioritize this. We are open for contribution :)
Let us know either way. Thanks!!

**Comment by grzesuav** [comment]
thanks :)

**Comment by azooinmyluggage** [comment]
@grzesuav PR or no PR? :)
Do let us know. Ok both ways

**Comment by grzesuav** [comment]
hi, unfortunately cannot commit to anything in near future

**Comment by ds-ms** [comment]
@shigupt202 would you like to pick this up?

**Comment by ajinkya599** [comment]
<ins>**CONTAINER SCAN - V1**</ins>

Container Scan GitHub action has been in v0 for about a year now. Here’s a bunch of enhancements we’re proposing to make the experience of customers better. 

<ins>**CREW**</ins>:
@ajinkya599
@ds-ms 
@shigupt202 

<ins>**PROBLEM STATEMENT**</ins>:
Let’s say you are to scan `image1` and `image2` in your container registry. Your snippet of workflow currently would look like this:

```yaml
- uses: azure/container-scan@v0
  with:
    image-name: loginServerUrl/myImage1
    username: ${{ secrets.DOCKER_USERNAME }}
    password: ${{ secrets.DOCKER_PASSWORD }}
- uses: azure/container-scan@v0
  with:
    image-name: loginServerUrl/myImage2
    username: ${{ secrets.DOCKER_USERNAME }}
    password: ${{ secrets.DOCKER_PASSWORD }}
```

Although both the images are in the same registry, we have to add the action multiple times. This proposal is to reduce the duplication of the same snippet to ensure a cleaner workflow as well as making the `container-scan` action more efficient.

<ins>**FEATURE REQUEST**</ins>:
Allow users in `container-scan` to scan multiple docker images in one go. 
The new workflow with our proposal would look like this:

``` yaml
- uses: azure/container-scan@v1
  with:
    images: |
      loginServerUrl/my-image1
      loginServerUrl/my-image2
    username: ${{ secrets.DOCKER_USERNAME }}
    password: ${{ secrets.DOCKER_PASSWORD }}
```

Solving this problem isn’t straightforward, we have listed out the requirements and potential solutions we’ve identified: 


<ins>**SOLUTION**</ins>:

| Requirement | Solution |
| ----------- | ----------- |
| Input for multiple images | 1. Continue with the same input `image-name` and use `image-names` for multiple images. <br> 2. [BREAKING] Remove `image-name` and include `images` for single as well as multiple images. |
| Allowedlist file | 1. Use the same list of vulnerabilities for all the images. <br> 2. Add image specific nodes in the file, parallel to `general` (example below) |
| Scan-report | 1. Create a new output variable called `scan-reports` for multiple images, and keep the existing `scan-report` for single image scan.<br> 2. [BREAKING]<br>  &nbsp; &nbsp; a. Update the structure of the report and make it an array of jsons in a single file.<br>  &nbsp; &nbsp; b. Create multiple files for each scan and make the output variable (`scan-reports`) an array of <image path>. |
| Check-run for scan summary | 1. Create a separate check-run for each image scan. Showing summary of all the scans may not be possible because of character limit with check runs. |
| Registry credentials | 1. Support only single registry, to avoid taking inputs for multiple registry credentials and their mapping with the image. For scenarios with images from different registries, the user can pull the images on the runner before running this action. |


- [Example]: AllowedList with image specific nodes:
  ``` yaml
  general:
   vulnerabilities:
     - CVE-2003-1307
     - CVE-2011-3374
   bestPracticeViolations:
     - CIS-DI-0005
     - DKL-DI-0006
  image-name-1:
   vulnerabilities:
     - CVE-2003-2207
     - CVE-2011-9074
   bestPracticeViolations:
     - CIS-DI-0205
     - DKL-DI-1106
  ```

- <ins>**Solution 1**</ins>:
In this approach, we try to maintain **back-compat** and update v0 version of the action with the following changes:
  - Introduce input `image-names` which is a newline separated list of images to be scanned. If `image-names` is provided, ignore `image-name` input.
  - Start supporting **image specific nodes** in **allowedList** file.
  - Introduce a **new output** variable **scan-reports** which is an array of individual scan-report file paths **separated by comma**. Example scan-reports:
`temp/scan-report-image-1,temp/scan-report-image-2`
  - Create **check-runs** for each scanned image with the details of scan.

- <ins>**Solution 2**</ins>:
In this approach, we introduce a new version v1 for the action that has breaking changes:
  - Replace `image-name` input by `images` input, which is a newline separated list of images to be scanned.
  - Start supporting **image specific nodes** in **allowedList** file.
  - Replace `scan-report` output variable with `scan-reports` which is an array of individual scan-report file paths **separated by comma**. Example scan-reports:
`temp/scan-report-image-1,temp/scan-report-image-2`
  - Create **check-runs** for each scanned image with the details of scan.



- <ins>**Side effects**</ins>:
Today, [azure/publish-security-assesments](https://github.com/azure/publish-security-assessments) understands the `scan-report` generated by `container-scan`. Currently, it directly consumes the result of container scan using syntax like `${{ steps.container_scan.outputs.scan-report-path }}` as shown in the snippet below:
  ```yaml
  - run: docker build . -t contoso.azurecr.io/k8sdemo:${{ github.sha }}
      
  - name: Scan container image for vulnerabilities
    id: container_scan
    uses: Azure/container-scan@v0
    with:
      image-name: contoso.azurecr.io/k8sdemo:${{ github.sha }}
   
  - name: Publish container scan results to ASC
    uses: azure/publish-security-assessments@v1
    with:
      subscription-token: ${{ secrets.asc_subscription_token }}
      instrumentation-key: ${{ secrets.ai_instrumentation_key }}
      scan-results-path: ${{ steps.container_scan.outputs.scan-report-path }}
  ```
  - This integration will **keep working** if we **don’t modify** the `scan-report schema`. There will be a requirement to have an **extra step** to **parse** the right scan report path in case of multiple scans though. We can **document** this.
  - If we introduce **breaking changes** in `scan-report schema`, we will need to **modify the implementation** to understand this change. (Note that the integration will still keep working with v0 version of container-scan action)
