### ISSUE TITLE
Failed to download trivy

### ISSUE THREAD

**Issue by scottwestover** [Azure/container-scan#66]
We are trying to integrate this action with one of our current workflows in a private repo, but our workflow keeps failing with the following error:

```
Error: Failed to download trivy from https://github.com/aquasecurity/trivy/releases/download/v0.16.0/trivy_0.16.0_Linux-64bit.tar.gz
```

I went ahead and enabled additional logging by setting the `ACTIONS_RUNNER_DEBUG` and `ACTIONS_STEP_DEBUG` secrets to `true`, and we are seeing the following logs:

```
Could not find allowedlist file.
##[debug]Downloading https://api.github.com/repos/aquasecurity/trivy/releases/latest
##[debug]Downloading /home/runner/work/_temp/8472635f-cf05-4075-a5c2-b755d65851c4
##[debug]download complete
##[debug]isExplicit: 0.16.0
##[debug]explicit? true
##[debug]checking cache: /opt/hostedtoolcache/trivy/0.16.0/x64
##[debug]not found
##[debug]Could not find trivy in cache, downloading from https://github.com/aquasecurity/trivy/releases/download/v0.16.0/trivy_0.16.0_Linux-64bit.tar.gz
##[debug]Downloading https://github.com/aquasecurity/trivy/releases/download/v0.16.0/trivy_0.16.0_Linux-64bit.tar.gz
##[debug]Downloading /home/runner/work/****/****/_temp/tools/trivy
Error: Failed to download trivy from https://github.com/aquasecurity/trivy/releases/download/v0.16.0/trivy_0.16.0_Linux-64bit.tar.gz
##[debug]Node Action run completed with exit code 1
##[debug]Finishing: Scan Docker Image
```

Additional information about environment:
```
Current runner version: '2.277.1'
Operating System
  Ubuntu
  20.04.2
  LTS
Virtual Environment
  Environment: ubuntu-20.04
  Version: 20210208.0
  Included Software: https://github.com/actions/virtual-environments/blob/ubuntu20/20210208.0/images/linux/Ubuntu2004-README.md
```

By chance, has anyone else ran into this issue before?

**Comment by shigupt202** [comment]
@scottwestover Are you using a private runner to run this workflow? It may be possible that the firewall rules on the runner are not allowing the action to download the tool. If you're using GitHub hosted runners, then this shouldn't be the problem.

**Comment by ds-ms** [comment]
@shigupt202 if that's the case, we should consider adding support for downloading this behind a proxy?

**Comment by scottwestover** [comment]
@shigupt202 Thanks for the quick response. We are using the GitHub hosted runner. In this particular repo, we are trying to run the action on a branch that is not the default branch for the repo. After some more testing, I was able to get the action to work correct on the default branch for the repo, but if I have a workflow that runs on a non default branch, the action fails to run.

As an example, if I have the following configuration:
```
name: Scott Test

on:
  push:
    branches:
      - develop

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tf_version: [ "0.14.2" ]
      fail-fast: true

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Scan Docker Image
        uses: azure/container-scan@v0
        with:
          image-name: foo:bar
```

The action fails to download `trivy`.

However if I use the following configuration:
```
name: Scott Test 2

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tf_version: [ "0.14.2" ]
      fail-fast: true

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Scan Docker Image
        uses: azure/container-scan@v0
        with:
          image-name: foo:bar
```

The action successfully downloads `trivy`, and proceeds to fail due to the fake image.

I tried recreating this issue in a separate repo, but I have not been able to reproduce it.

For the time being, I have moved the `container-scan` action to be part of our workflow in our `master` branch and I have commented it out of our workflow for our `develop` branch.
