### ISSUE TITLE
Incorrect and incomplete documentation of allowedlist.yaml and other ignores

### ISSUE THREAD

**Issue by erzz** [Azure/container-scan#76]
Whitelisting according to docs doesn't work. Here are my findings so far

Readme currently states to use `.github/containerscan/whitelist.yaml` when digging through source it shows you actually look for `.github/containerscan/allowedlist.yaml`

Source also seems to indicate that you also observe the standard ignore files for both trivy and dockle. Thus is would be nice if you indicated that in the documentation too 

But having tried both whitelist.yaml and allowedlist.yaml - neither seems to impact the findings or exit code of the job.

Workflow example:

```
image-scan:
    name: Image Scan & Lint
    needs: build-image
    runs-on: ubuntu-latest
    steps:
      - uses: azure/container-scan@v0
        name: Scan Image
        id: container-scan
        with:
          image-name: ${{ needs.build-image.outputs.image-name }}
          username: ******
          password: ******
          severity-threshold: HIGH
          run-quality-checks: true
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: trivy-image-scan
          path: ${{ steps.container-scan.outputs.scan-report-path }}
```

allowedlist / whitelist example (not that I intend to use these settings but just trying to impact the findings :) )

```
general:
  vulnerabilities:
    - CVE-2021-27290
  bestPracticeViolations:
    - CIS-DI-0006
    - DKL-DI-0003
    - DKL-DI-0004
    - CIS-DI-0005
    - DKL-LI-0003
```
