### ISSUE TITLE
SARIF support?

### ISSUE THREAD

**Issue by robert-scheck** [Azure/container-scan#95]
Is there any chance for SARIF support (SARIF-compatible output file)? That would allow to use `github/codeql-action/upload-sarif@v1` in workflows, e.g.:

```
- name: Upload SARIF report
  uses: github/codeql-action/upload-sarif@v1
  with:
    sarif_file: ${{ steps.scan.outputs.sarif }}
```

See also: https://docs.github.com/en/code-security/secure-coding/integrating-with-code-scanning/uploading-a-sarif-file-to-github

**Comment by ajinkya599** [comment]
@pulkitaggarwl - Seeking your thoughts on this feature request.

**Comment by pulkitaggarwl** [comment]
thanks @robert-scheck  for raising the ask. we dont have this as part of our backlog currently. would you be willing to contribute to the action to add this functionality.

**Comment by rm3l** [comment]
Hi there !
I was also interested in this feature. Before seeing this issue, I set out to build [this other Action](https://github.com/rm3l/container-scan-to-sarif-action) to convert the output to SARIF.
It should therefore be possible to support SARIF by adding a new step in your Workflows, like so:
```yaml
- name: Scan Container Image
  id: scan
  uses: Azure/container-scan@v0.1
  with:
    image-name: my-container-image
    
- name: Convert Container Scan Report to SARIF
  id: scan-to-sarif
  uses: rm3l/container-scan-to-sarif-action@v1
  if: ${{ always() }}
  with:
    converter-version: 0.4.0
    input-file: ${{ steps.scan.outputs.scan-report-path }}

- name: Upload SARIF reports to GitHub Security tab
  uses: github/codeql-action/upload-sarif@v1
  if: ${{ always() }}
  with:
    sarif_file: ${{ steps.scan-to-sarif.outputs.sarif-report-path }}
```

Let me know your thoughts about this.
